version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    depends_on:
      - mysqldb
      - redis
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=mysqldb
      - REDIS_HOST=redis
    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./:/app

volumes:
  db:
